// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientInfo.proto

#include "ClientInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace com {
namespace sqage {
namespace xiyou {
namespace gateway {
namespace client {
class ClientInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientInfo>
      _instance;
} _ClientInfo_default_instance_;
}  // namespace client
}  // namespace gateway
}  // namespace xiyou
}  // namespace sqage
}  // namespace com
namespace protobuf_ClientInfo_2eproto {
void InitDefaultsClientInfoImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::com::sqage::xiyou::gateway::client::_ClientInfo_default_instance_;
    new (ptr) ::com::sqage::xiyou::gateway::client::ClientInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::sqage::xiyou::gateway::client::ClientInfo::InitAsDefaultInstance();
}

void InitDefaultsClientInfo() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsClientInfoImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, usertype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, username_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, clientid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, channel_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, phonetype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, gputype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, networkmode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, resourceversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, programversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, otherinfo_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, mac_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, idfa_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, androidid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, deviceid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, ime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::com::sqage::xiyou::gateway::client::ClientInfo, platform_),
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  ~0u,
  9,
  10,
  11,
  12,
  13,
  14,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 21, sizeof(::com::sqage::xiyou::gateway::client::ClientInfo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::com::sqage::xiyou::gateway::client::_ClientInfo_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "ClientInfo.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020ClientInfo.proto\022\036com.sqage.xiyou.gate"
      "way.client\"\257\002\n\nClientInfo\022\020\n\010userType\030\001 "
      "\002(\t\022\020\n\010userName\030\002 \002(\t\022\020\n\010clientId\030\003 \002(\t\022"
      "\017\n\007channel\030\004 \002(\t\022\021\n\tphoneType\030\005 \002(\t\022\017\n\007g"
      "puType\030\006 \002(\t\022\023\n\013networkMode\030\007 \002(\t\022\027\n\017res"
      "ourceVersion\030\010 \002(\t\022\026\n\016programVersion\030\t \002"
      "(\t\022\021\n\totherInfo\030\n \003(\t\022\013\n\003mac\030\013 \002(\t\022\014\n\004id"
      "fa\030\014 \001(\t\022\021\n\tandroidId\030\r \001(\t\022\020\n\010deviceId\030"
      "\016 \001(\t\022\013\n\003ime\030\017 \001(\t\022\020\n\010platform\030\020 \002(\tB\002P\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 360);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ClientInfo.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ClientInfo_2eproto
namespace com {
namespace sqage {
namespace xiyou {
namespace gateway {
namespace client {

// ===================================================================

void ClientInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientInfo::kUserTypeFieldNumber;
const int ClientInfo::kUserNameFieldNumber;
const int ClientInfo::kClientIdFieldNumber;
const int ClientInfo::kChannelFieldNumber;
const int ClientInfo::kPhoneTypeFieldNumber;
const int ClientInfo::kGpuTypeFieldNumber;
const int ClientInfo::kNetworkModeFieldNumber;
const int ClientInfo::kResourceVersionFieldNumber;
const int ClientInfo::kProgramVersionFieldNumber;
const int ClientInfo::kOtherInfoFieldNumber;
const int ClientInfo::kMacFieldNumber;
const int ClientInfo::kIdfaFieldNumber;
const int ClientInfo::kAndroidIdFieldNumber;
const int ClientInfo::kDeviceIdFieldNumber;
const int ClientInfo::kImeFieldNumber;
const int ClientInfo::kPlatformFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientInfo::ClientInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_ClientInfo_2eproto::InitDefaultsClientInfo();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.sqage.xiyou.gateway.client.ClientInfo)
}
ClientInfo::ClientInfo(const ClientInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      otherinfo_(from.otherinfo_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  usertype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_usertype()) {
    usertype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usertype_);
  }
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_username()) {
    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  clientid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_clientid()) {
    clientid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clientid_);
  }
  channel_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_channel()) {
    channel_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channel_);
  }
  phonetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_phonetype()) {
    phonetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.phonetype_);
  }
  gputype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_gputype()) {
    gputype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gputype_);
  }
  networkmode_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_networkmode()) {
    networkmode_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.networkmode_);
  }
  resourceversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_resourceversion()) {
    resourceversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.resourceversion_);
  }
  programversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_programversion()) {
    programversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.programversion_);
  }
  mac_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_mac()) {
    mac_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mac_);
  }
  idfa_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_idfa()) {
    idfa_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.idfa_);
  }
  androidid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_androidid()) {
    androidid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.androidid_);
  }
  deviceid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_deviceid()) {
    deviceid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deviceid_);
  }
  ime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_ime()) {
    ime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ime_);
  }
  platform_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_platform()) {
    platform_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.platform_);
  }
  // @@protoc_insertion_point(copy_constructor:com.sqage.xiyou.gateway.client.ClientInfo)
}

void ClientInfo::SharedCtor() {
  _cached_size_ = 0;
  usertype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clientid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  phonetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gputype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  networkmode_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  resourceversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  programversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mac_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  idfa_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  androidid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deviceid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  platform_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ClientInfo::~ClientInfo() {
  // @@protoc_insertion_point(destructor:com.sqage.xiyou.gateway.client.ClientInfo)
  SharedDtor();
}

void ClientInfo::SharedDtor() {
  usertype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clientid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  phonetype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gputype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  networkmode_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  resourceversion_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  programversion_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mac_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  idfa_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  androidid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deviceid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  platform_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ClientInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientInfo::descriptor() {
  ::protobuf_ClientInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ClientInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientInfo& ClientInfo::default_instance() {
  ::protobuf_ClientInfo_2eproto::InitDefaultsClientInfo();
  return *internal_default_instance();
}

ClientInfo* ClientInfo::New(::google::protobuf::Arena* arena) const {
  ClientInfo* n = new ClientInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:com.sqage.xiyou.gateway.client.ClientInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  otherinfo_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!usertype_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*usertype_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!username_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*username_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(!clientid_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*clientid_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(!channel_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*channel_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(!phonetype_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*phonetype_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(!gputype_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*gputype_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000040u) {
      GOOGLE_DCHECK(!networkmode_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*networkmode_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000080u) {
      GOOGLE_DCHECK(!resourceversion_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*resourceversion_.UnsafeRawStringPointer())->clear();
    }
  }
  if (cached_has_bits & 32512u) {
    if (cached_has_bits & 0x00000100u) {
      GOOGLE_DCHECK(!programversion_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*programversion_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000200u) {
      GOOGLE_DCHECK(!mac_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*mac_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000400u) {
      GOOGLE_DCHECK(!idfa_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*idfa_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000800u) {
      GOOGLE_DCHECK(!androidid_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*androidid_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00001000u) {
      GOOGLE_DCHECK(!deviceid_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*deviceid_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00002000u) {
      GOOGLE_DCHECK(!ime_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*ime_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00004000u) {
      GOOGLE_DCHECK(!platform_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*platform_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ClientInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.sqage.xiyou.gateway.client.ClientInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string userType = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usertype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->usertype().data(), static_cast<int>(this->usertype().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.userType");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string userName = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->username().data(), static_cast<int>(this->username().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.userName");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string clientId = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_clientid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->clientid().data(), static_cast<int>(this->clientid().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.clientId");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string channel = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_channel()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->channel().data(), static_cast<int>(this->channel().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.channel");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string phoneType = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phonetype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->phonetype().data(), static_cast<int>(this->phonetype().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.phoneType");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string gpuType = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gputype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->gputype().data(), static_cast<int>(this->gputype().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.gpuType");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string networkMode = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_networkmode()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->networkmode().data(), static_cast<int>(this->networkmode().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.networkMode");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string resourceVersion = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_resourceversion()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->resourceversion().data(), static_cast<int>(this->resourceversion().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.resourceVersion");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string programVersion = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_programversion()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->programversion().data(), static_cast<int>(this->programversion().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.programVersion");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string otherInfo = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_otherinfo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->otherinfo(this->otherinfo_size() - 1).data(),
            static_cast<int>(this->otherinfo(this->otherinfo_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.otherInfo");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string mac = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mac()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->mac().data(), static_cast<int>(this->mac().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.mac");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string idfa = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_idfa()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->idfa().data(), static_cast<int>(this->idfa().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.idfa");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string androidId = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_androidid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->androidid().data(), static_cast<int>(this->androidid().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.androidId");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string deviceId = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deviceid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->deviceid().data(), static_cast<int>(this->deviceid().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.deviceId");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string ime = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ime()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->ime().data(), static_cast<int>(this->ime().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.ime");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string platform = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(130u /* 130 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_platform()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->platform().data(), static_cast<int>(this->platform().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "com.sqage.xiyou.gateway.client.ClientInfo.platform");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.sqage.xiyou.gateway.client.ClientInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.sqage.xiyou.gateway.client.ClientInfo)
  return false;
#undef DO_
}

void ClientInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.sqage.xiyou.gateway.client.ClientInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string userType = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->usertype().data(), static_cast<int>(this->usertype().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.userType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->usertype(), output);
  }

  // required string userName = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.userName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->username(), output);
  }

  // required string clientId = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->clientid().data(), static_cast<int>(this->clientid().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.clientId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->clientid(), output);
  }

  // required string channel = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->channel().data(), static_cast<int>(this->channel().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.channel");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->channel(), output);
  }

  // required string phoneType = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->phonetype().data(), static_cast<int>(this->phonetype().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.phoneType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->phonetype(), output);
  }

  // required string gpuType = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->gputype().data(), static_cast<int>(this->gputype().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.gpuType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->gputype(), output);
  }

  // required string networkMode = 7;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->networkmode().data(), static_cast<int>(this->networkmode().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.networkMode");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->networkmode(), output);
  }

  // required string resourceVersion = 8;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->resourceversion().data(), static_cast<int>(this->resourceversion().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.resourceVersion");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->resourceversion(), output);
  }

  // required string programVersion = 9;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->programversion().data(), static_cast<int>(this->programversion().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.programVersion");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->programversion(), output);
  }

  // repeated string otherInfo = 10;
  for (int i = 0, n = this->otherinfo_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->otherinfo(i).data(), static_cast<int>(this->otherinfo(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.otherInfo");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      10, this->otherinfo(i), output);
  }

  // required string mac = 11;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->mac().data(), static_cast<int>(this->mac().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.mac");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->mac(), output);
  }

  // optional string idfa = 12;
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->idfa().data(), static_cast<int>(this->idfa().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.idfa");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->idfa(), output);
  }

  // optional string androidId = 13;
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->androidid().data(), static_cast<int>(this->androidid().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.androidId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->androidid(), output);
  }

  // optional string deviceId = 14;
  if (cached_has_bits & 0x00001000u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->deviceid().data(), static_cast<int>(this->deviceid().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.deviceId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      14, this->deviceid(), output);
  }

  // optional string ime = 15;
  if (cached_has_bits & 0x00002000u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ime().data(), static_cast<int>(this->ime().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.ime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      15, this->ime(), output);
  }

  // required string platform = 16;
  if (cached_has_bits & 0x00004000u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->platform().data(), static_cast<int>(this->platform().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.platform");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      16, this->platform(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.sqage.xiyou.gateway.client.ClientInfo)
}

::google::protobuf::uint8* ClientInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:com.sqage.xiyou.gateway.client.ClientInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string userType = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->usertype().data(), static_cast<int>(this->usertype().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.userType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->usertype(), target);
  }

  // required string userName = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.userName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->username(), target);
  }

  // required string clientId = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->clientid().data(), static_cast<int>(this->clientid().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.clientId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->clientid(), target);
  }

  // required string channel = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->channel().data(), static_cast<int>(this->channel().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.channel");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->channel(), target);
  }

  // required string phoneType = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->phonetype().data(), static_cast<int>(this->phonetype().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.phoneType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->phonetype(), target);
  }

  // required string gpuType = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->gputype().data(), static_cast<int>(this->gputype().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.gpuType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->gputype(), target);
  }

  // required string networkMode = 7;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->networkmode().data(), static_cast<int>(this->networkmode().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.networkMode");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->networkmode(), target);
  }

  // required string resourceVersion = 8;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->resourceversion().data(), static_cast<int>(this->resourceversion().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.resourceVersion");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->resourceversion(), target);
  }

  // required string programVersion = 9;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->programversion().data(), static_cast<int>(this->programversion().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.programVersion");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->programversion(), target);
  }

  // repeated string otherInfo = 10;
  for (int i = 0, n = this->otherinfo_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->otherinfo(i).data(), static_cast<int>(this->otherinfo(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.otherInfo");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(10, this->otherinfo(i), target);
  }

  // required string mac = 11;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->mac().data(), static_cast<int>(this->mac().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.mac");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->mac(), target);
  }

  // optional string idfa = 12;
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->idfa().data(), static_cast<int>(this->idfa().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.idfa");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->idfa(), target);
  }

  // optional string androidId = 13;
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->androidid().data(), static_cast<int>(this->androidid().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.androidId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->androidid(), target);
  }

  // optional string deviceId = 14;
  if (cached_has_bits & 0x00001000u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->deviceid().data(), static_cast<int>(this->deviceid().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.deviceId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        14, this->deviceid(), target);
  }

  // optional string ime = 15;
  if (cached_has_bits & 0x00002000u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ime().data(), static_cast<int>(this->ime().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.ime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        15, this->ime(), target);
  }

  // required string platform = 16;
  if (cached_has_bits & 0x00004000u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->platform().data(), static_cast<int>(this->platform().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "com.sqage.xiyou.gateway.client.ClientInfo.platform");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        16, this->platform(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.sqage.xiyou.gateway.client.ClientInfo)
  return target;
}

size_t ClientInfo::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:com.sqage.xiyou.gateway.client.ClientInfo)
  size_t total_size = 0;

  if (has_usertype()) {
    // required string userType = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usertype());
  }

  if (has_username()) {
    // required string userName = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  if (has_clientid()) {
    // required string clientId = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->clientid());
  }

  if (has_channel()) {
    // required string channel = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->channel());
  }

  if (has_phonetype()) {
    // required string phoneType = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->phonetype());
  }

  if (has_gputype()) {
    // required string gpuType = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->gputype());
  }

  if (has_networkmode()) {
    // required string networkMode = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->networkmode());
  }

  if (has_resourceversion()) {
    // required string resourceVersion = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->resourceversion());
  }

  if (has_programversion()) {
    // required string programVersion = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->programversion());
  }

  if (has_mac()) {
    // required string mac = 11;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mac());
  }

  if (has_platform()) {
    // required string platform = 16;
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->platform());
  }

  return total_size;
}
size_t ClientInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.sqage.xiyou.gateway.client.ClientInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x000043ff) ^ 0x000043ff) == 0) {  // All required fields are present.
    // required string userType = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usertype());

    // required string userName = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());

    // required string clientId = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->clientid());

    // required string channel = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->channel());

    // required string phoneType = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->phonetype());

    // required string gpuType = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->gputype());

    // required string networkMode = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->networkmode());

    // required string resourceVersion = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->resourceversion());

    // required string programVersion = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->programversion());

    // required string mac = 11;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mac());

    // required string platform = 16;
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->platform());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated string otherInfo = 10;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->otherinfo_size());
  for (int i = 0, n = this->otherinfo_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->otherinfo(i));
  }

  if (_has_bits_[8 / 32] & 15360u) {
    // optional string idfa = 12;
    if (has_idfa()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->idfa());
    }

    // optional string androidId = 13;
    if (has_androidid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->androidid());
    }

    // optional string deviceId = 14;
    if (has_deviceid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->deviceid());
    }

    // optional string ime = 15;
    if (has_ime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ime());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.sqage.xiyou.gateway.client.ClientInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClientInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.sqage.xiyou.gateway.client.ClientInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.sqage.xiyou.gateway.client.ClientInfo)
    MergeFrom(*source);
  }
}

void ClientInfo::MergeFrom(const ClientInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.sqage.xiyou.gateway.client.ClientInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  otherinfo_.MergeFrom(from.otherinfo_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_usertype();
      usertype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usertype_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_username();
      username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_clientid();
      clientid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.clientid_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_channel();
      channel_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channel_);
    }
    if (cached_has_bits & 0x00000010u) {
      set_has_phonetype();
      phonetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.phonetype_);
    }
    if (cached_has_bits & 0x00000020u) {
      set_has_gputype();
      gputype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gputype_);
    }
    if (cached_has_bits & 0x00000040u) {
      set_has_networkmode();
      networkmode_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.networkmode_);
    }
    if (cached_has_bits & 0x00000080u) {
      set_has_resourceversion();
      resourceversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.resourceversion_);
    }
  }
  if (cached_has_bits & 32512u) {
    if (cached_has_bits & 0x00000100u) {
      set_has_programversion();
      programversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.programversion_);
    }
    if (cached_has_bits & 0x00000200u) {
      set_has_mac();
      mac_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mac_);
    }
    if (cached_has_bits & 0x00000400u) {
      set_has_idfa();
      idfa_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.idfa_);
    }
    if (cached_has_bits & 0x00000800u) {
      set_has_androidid();
      androidid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.androidid_);
    }
    if (cached_has_bits & 0x00001000u) {
      set_has_deviceid();
      deviceid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deviceid_);
    }
    if (cached_has_bits & 0x00002000u) {
      set_has_ime();
      ime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ime_);
    }
    if (cached_has_bits & 0x00004000u) {
      set_has_platform();
      platform_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.platform_);
    }
  }
}

void ClientInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.sqage.xiyou.gateway.client.ClientInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientInfo::CopyFrom(const ClientInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.sqage.xiyou.gateway.client.ClientInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x000043ff) != 0x000043ff) return false;
  return true;
}

void ClientInfo::Swap(ClientInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientInfo::InternalSwap(ClientInfo* other) {
  using std::swap;
  otherinfo_.InternalSwap(&other->otherinfo_);
  usertype_.Swap(&other->usertype_);
  username_.Swap(&other->username_);
  clientid_.Swap(&other->clientid_);
  channel_.Swap(&other->channel_);
  phonetype_.Swap(&other->phonetype_);
  gputype_.Swap(&other->gputype_);
  networkmode_.Swap(&other->networkmode_);
  resourceversion_.Swap(&other->resourceversion_);
  programversion_.Swap(&other->programversion_);
  mac_.Swap(&other->mac_);
  idfa_.Swap(&other->idfa_);
  androidid_.Swap(&other->androidid_);
  deviceid_.Swap(&other->deviceid_);
  ime_.Swap(&other->ime_);
  platform_.Swap(&other->platform_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClientInfo::GetMetadata() const {
  protobuf_ClientInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ClientInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace client
}  // namespace gateway
}  // namespace xiyou
}  // namespace sqage
}  // namespace com

// @@protoc_insertion_point(global_scope)
